### ISSUE TITLE
Update page

### ISSUE THREAD

**Issue by grodeska** [CityCamp/citycamp.github.io#1]
Update agenda section:

Check-in and breakfast
8:30 a.m.
"State of SF” presentations & discussions
9:00 a.m.
Open space planning
11:00 a.m.
Lunch
12:00 p.m.
Open space sessions
12:30 p.m.
Report back & closing
4:30 p.m.
Social hour
5:00 p.m.

Add speakers section:

Jay Nath, Chief Innovation Officer, SF Mayor's Office of Civic Innovation
Joy Bonaguro, Chief Data Office, SF Mayor's Office
Francis Zamora, Public Information Officer, SF Department of Emergency Management
Kristin Hogan, External Affairs Specialist, SF Department of Emergency Management
Dan Parham, Founder, Neighborland

**Comment by grodeska** [comment]
Hey Luke, CfSF wants to add their logo to the sponsor section. From Jesse:

"I don't think the font needs changing - just smack this logo up next to "Code for San Francisco" if possible."
![c4sf-logo](https://cloud.githubusercontent.com/assets/7856430/5631406/27c74e12-957b-11e4-8cb7-e60259883e6b.jpg)

**Comment by lukefretwell** [comment]
Done.
